spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
  datasource:
    url: 127.0.0.1:3306
    name: otr_accident_car
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration